import { db } from '../firebase.js';
import { collection, getDocs, doc, getDoc } from 'https://www.gstatic.com/firebasejs/12.2.1/firebase-firestore.js';

const esc = s => String(s ?? '').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const list=document.getElementById('lotteryList');
const LANG='tl_lang';
const translations={
 en:{navCheck:'Check Ticket',navHome:'Home',heroTitle:'Your chance. Your ticket. Your future.',heroText:'Choose an available lottery, submit your payment proof, and track your ticket status online.',viewLotteries:'View Lotteries',checkMyTicket:'Check my ticket',available:'Available lotteries',manualVerification:'Manual verification',howTitle:'Simple from start to finish',step1Title:'Choose',step1Text:'Select the lottery you want to enter.',step2Title:'Submit proof',step2Text:'Provide a reference number or payment screenshot.',step3Title:'Get your ticket',step3Text:'After approval, your ticket numbers are assigned.',footerText:'Please keep your phone number. You can use it anytime to check your ticket status.',contactEyebrow:'CONTACT US',contactTitle:'Need help?',contactText:'Contact us on WhatsApp for assistance with your ticket request.',contactWhatsApp:'Contact us on WhatsApp',developedBy:'Developed by YOAS Digital Solution'},
 ti:{navCheck:'መረጋገፂ ቲኬት',navHome:'ቀዳማይ ገፅ',heroTitle:'ዕድልኻ። ቲኬትካ። መፃኢኻ።',heroText:'ዝኸፈተ ሎተሪ ምረፅ፣ መረጋገፂ ክፍሊት ኣቕርብ፣ ኩነታት ቲኬትካ ኦንላይን ተኸታተል።',viewLotteries:'ሎተሪታት ርአ',checkMyTicket:'ቲኬተይ ኣረጋግፅ',available:'ዝተኸፍቱ ሎተሪታት',manualVerification:'ተራእዩ ዝረጋገፅ',howTitle:'ካብ መጀመርታ ክሳብ መወዳእታ ቀሊል',step1Title:'ምረፅ',step1Text:'ክትሳተፍ ዝደለኻዮ ሎተሪ ምረፅ።',step2Title:'መረጋገፂ ኣቕርብ',step2Text:'ቁፅሪ መረጋገፂ ወይ ስክሪንሾት ክፍሊት ኣቕርብ።',step3Title:'ቲኬትካ ተቐበል',step3Text:'ድሕሪ ምፅዳቕ፣ ቁፅሪ ቲኬትካ ይምደብ።',footerText:'ቁፅሪ ስልክኻ ሓዞ። ኩነታት ቲኬትካ ኣብ ዝኾነ ግዜ ክተረጋግፅ ትኽእል።',contactEyebrow:'ርኸቡና',contactTitle:'ሓገዝ ደሊኻ?',contactText:'ብዛዕባ ትእዛዝ ቲኬትካ ሓገዝ እንተደሊኻ፣ ብWhatsApp ርኸቡና።',contactWhatsApp:'ብWhatsApp ርኸቡና',developedBy:'ብ YOAS Digital Solution ዝተሰርሐ'}
};
function getLang(){return localStorage.getItem(LANG)||'en'}
function applyLang(){const lang=getLang(),t=translations[lang];document.documentElement.lang=lang==='ti'?'ti':'en';document.querySelectorAll('[data-i18n]').forEach(el=>{const k=el.dataset.i18n;if(t[k])el.textContent=t[k]});const b=document.getElementById('langToggle');if(b)b.textContent=lang==='en'?'ትግርኛ':'English'}
window.addEventListener('storage',applyLang);document.getElementById('langToggle')?.addEventListener('click',e=>{e.preventDefault();localStorage.setItem(LANG,getLang()==='en'?'ti':'en');location.reload()});
function statusText(status){return status==='active'?'OPEN':status==='upcoming'?'COMING SOON':status==='drawn'?'DRAW COMPLETED':'CLOSED'}
function setWhatsAppContact(number){const el=document.getElementById('whatsappContact');if(!el)return;const digits=String(number||'').replace(/[^0-9]/g,'');if(!digits){el.hidden=true;return;}el.href=`https://wa.me/${digits}`;el.hidden=false;}
async function loadSiteSettings(){try{const snap=await getDoc(doc(db,'settings','site'));if(snap.exists())setWhatsAppContact(snap.data().whatsappNumber||'')}catch(e){console.warn('Could not load contact settings:',e.message)}}
async function home(){try{const snap=await getDocs(collection(db,'lotteries'));const lots=snap.docs.map(d=>({id:d.id,...d.data()})).filter(x=>x.status!=='hidden');lots.sort((a,b)=>(a.status==='active'?0:1)-(b.status==='active'?0:1));list.innerHTML=lots.length?lots.map(x=>{const active=x.status==='active';return `<article class="card lottery-card"><div class="card-top"><span class="status-badge status-${esc(x.status)}">${statusText(x.status)}</span><span class="price">${Number(x.price||0)} Birr</span></div><h2>${esc(x.name)}</h2><p class="muted">${esc(x.description||'Ticket numbers are assigned after approval.')}</p><div class="info-line"><span class="info-pill">${esc(x.min)} – ${esc(x.max)}</span></div><div class="card-actions">${active?`<a class="btn btn-primary full" href="buy.html?lot=${encodeURIComponent(x.id)}">${getLang()==='ti'?'ቲኬት ዓድግ':'Buy Ticket'} →</a>`:`<button class="btn full" disabled>${statusText(x.status)}</button>`}</div></article>`}).join(''):'<div class="loading-card">No lotteries are available yet.</div>'}catch(e){console.error(e);list.innerHTML='<div class="error">Unable to load lotteries. Please try again.</div>'}}
applyLang();loadSiteSettings();home();
