import { db, auth } from '../../firebase.js';
import { onAuthStateChanged, signOut } from 'https://www.gstatic.com/firebasejs/12.2.1/firebase-auth.js';
import { collection, getDocs, doc, getDoc, updateDoc, query, where, runTransaction, serverTimestamp } from 'https://www.gstatic.com/firebasejs/12.2.1/firebase-firestore.js';
import { phoneHash } from '../../js/phoneHash.js';
const $=id=>document.getElementById(id); const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let me=null, profile=null, lot=null;
$('logoutBtn').addEventListener('click',async()=>{await signOut(auth);location.href='login.html';});
$('refreshBtn').addEventListener('click',render); $('editBtn').addEventListener('click',editLottery);
onAuthStateChanged(auth,async u=>{if(!u){location.href='login.html';return;}me=u;try{const p=await getDoc(doc(db,'users',u.uid));if(!p.exists()||p.data().role!=='lotteryAdmin'){location.href='login.html';return;}profile=p.data();const ids=profile.lotteryIds||[];if(!ids.length)throw new Error('No lottery assigned to this account.');if(ids.length>1)console.warn('Multiple lottery IDs assigned; this dashboard currently uses the first one.');const s=await getDoc(doc(db,'lotteries',ids[0]));if(!s.exists())throw new Error('Assigned lottery no longer exists.');lot={id:s.id,...s.data()};await render();}catch(e){console.error(e);$('message').innerHTML=`<div class="error">${esc(e.message)}</div>`;}});
async function render(){if(!lot)return;$('lotteryName').textContent='· '+lot.name;$('lotteryInfo').innerHTML=`<p><b>${esc(lot.name)}</b> <span class="badge ${esc(lot.status)}">${esc(lot.status)}</span></p><p>Ticket price: <b>${Number(lot.price||0)} Birr</b></p><p>Number range: ${esc(lot.min)} – ${esc(lot.max)}</p>`;const rs=await getDocs(query(collection(db,'ticketRequests'),where('lotteryId','==',lot.id)));renderRequests(rs);}
function renderRequests(rs){$('requests').innerHTML=rs.docs.map(d=>{const x=d.data();return `<div class="row"><b>${esc(x.name)}</b> · ${esc(x.phone)}<br>${Number(x.quantity||1)} ticket(s) · ${Number(x.total||0)} Birr<br>Reference: ${esc(x.reference||'')}<br>Status: <b class="${esc(x.status)}">${esc(x.status)}</b>${x.ticketNumbers?.length?`<br>🎟️ ${x.ticketNumbers.map(n=>`<span class="badge">${esc(n)}</span>`).join(' ')}`:''}${x.status==='pending'?`<div class="actions"><button data-approve="${esc(d.id)}">✓ Approve</button><button class="danger" data-reject="${esc(d.id)}">✕ Reject</button></div>`:''}</div>`}).join('')||'<p class="muted">No requests yet.</p>';document.querySelectorAll('[data-approve]').forEach(b=>b.addEventListener('click',()=>approve(b.dataset.approve)));document.querySelectorAll('[data-reject]').forEach(b=>b.addEventListener('click',()=>reject(b.dataset.reject)));}
async function editLottery(){const name=prompt('Lottery name',lot.name);if(name===null)return;const price=Number(prompt('Ticket price (Birr)',lot.price));if(!price||price<=0)return alert('Invalid price.');try{await updateDoc(doc(db,'lotteries',lot.id),{name:name.trim(),price});lot={...lot,name:name.trim(),price};await render();$('message').innerHTML='<div class="success">Lottery updated.</div>';}catch(e){alert(e.message);}}
async function reject(id){try{const r=doc(db,'ticketRequests',id);const rs=await getDoc(r);const data=rs.data()||{};await updateDoc(r,{status:'rejected',reviewedBy:me.uid,reviewedAt:serverTimestamp()});const h=await phoneHash(data.phone||'');if(h)await updateDoc(doc(db,'publicStatus',h,'requests',id),{status:'rejected',reviewedAt:serverTimestamp()});await render();}catch(e){alert(e.message);}}
async function approve(id){if(!confirm('Approve this payment and assign random ticket number(s)?'))return;try{
 const initial=await getDoc(doc(db,'ticketRequests',id)); if(!initial.exists())throw new Error('Request not found.'); const initialData=initial.data(); const publicHash=await phoneHash(initialData.phone||'');
 await runTransaction(db,async tx=>{
   const reqRef=doc(db,'ticketRequests',id); const reqSnap=await tx.get(reqRef); if(!reqSnap.exists())throw new Error('Request not found.'); const x=reqSnap.data(); if(x.status!=='pending')throw new Error('This request has already been reviewed.'); if(x.lotteryId!==lot.id)throw new Error('Not authorized for this lottery.');
   const count=Math.max(1,Math.min(100,Number(x.quantity||1))); const range=Number(lot.max)-Number(lot.min)+1; if(count>range)throw new Error('Not enough ticket numbers in this lottery.');
   const picks=[]; let attempts=0;
   while(picks.length<count && attempts<count*80){attempts++;const n=Math.floor(Math.random()*range)+Number(lot.min);if(picks.includes(n))continue;const tRef=doc(db,'tickets',`${lot.id}_${n}`);const tSnap=await tx.get(tRef);if(tSnap.exists())continue;picks.push(n);tx.set(tRef,{lotteryId:lot.id,number:n,requestId:id,assignedAt:serverTimestamp(),assignedBy:me.uid});}
   if(picks.length<count)throw new Error('Could not find enough free ticket numbers.');
   tx.update(reqRef,{status:'approved',ticketNumbers:picks,reviewedBy:me.uid,reviewedAt:serverTimestamp()});
   if(publicHash) tx.update(doc(db,'publicStatus',publicHash,'requests',id),{status:'approved',ticketNumbers:picks,reviewedAt:serverTimestamp()});
 }); await render();$('message').innerHTML='<div class="success">Payment approved and ticket number(s) assigned.</div>';
 }catch(e){console.error(e);$('message').innerHTML=`<div class="error">${esc(e.message)}</div>`;}
}
